### PR TITLE
Move overloading of functions from Binding to RabbitClient

### PR DESCRIPTION
**Pull request by agustafson**
As discussed in #428, removing the overloaded functions in `Binding` and moving it all to `RabbitClient` so that the approach is consistent across both classes.

### CODE REVIEW

**Review by jbwheatley — APPROVED** [review]
This is cleaner - LGTM

**Comment by agustafson** [comment]
@Mergifyio rebase

**Comment by agustafson** [comment]
@mergifyio rebase

**Comment by agustafson** [comment]
@mergifyio merge

**Comment by agustafson** [comment]
@mergifyio update

**Comment by agustafson** [comment]
@Mergifyio update

**Comment by agustafson** [comment]
@Mergifyio merge

**Comment by agustafson** [comment]
@Mergifyio update

**Comment by jbwheatley** [comment]
merged into `series/4.x` (#497), so closing this

**Pull request closed without merging**
