### PR TITLE
Add explicit execution context configuration

### PR DESCRIPTION
**Pull request by retriku**
Adds configurable execution context while creating RabbitClient. Closes issue #694

### CODE REVIEW

**Comment by jbwheatley** [comment]
Yeah, think this looks like the most sensible way to add a configurable `ExecutionContext` 👍 

You will unfortunately have do some work to get mima to pass - I think you can do this by new functions with the added argument and deprecating/making package private the old one. i.e.
```scala
@deprecated("use other apply method with configurable execution context", "4.1.1")
private[interpreter] def apply[F[_]: Async](
      config: Fs2RabbitConfig,
      dispatcher: Dispatcher[F],
      sslContext: Option[SSLContext] = None,
      saslConfig: SaslConfig = DefaultSaslConfig.PLAIN,
      metricsCollector: Option[MetricsCollector] = None,
      threadFactory: Option[F[ThreadFactory]] = None
  ): F[RabbitClient[F]] = ???

def apply[F[_]: Async](
      config: Fs2RabbitConfig,
      dispatcher: Dispatcher[F],
      sslContext: Option[SSLContext] = None,
      saslConfig: SaslConfig = DefaultSaslConfig.PLAIN,
      metricsCollector: Option[MetricsCollector] = None,
      threadFactory: Option[F[ThreadFactory]] = None,
      executionContext: Option[F[ExecutionContext]] = None
  ): F[RabbitClient[F]] = ???
```

**Comment by retriku** [comment]
Hi @jbwheatley! I do not know how to solve these migration issues. Maybe we need to increment major version?

**Comment by retriku** [comment]
I introduced builder for RabbitClient. Please, review

**Comment by jbwheatley** [comment]
Awesome, the builder stuff is great 👍  

Can you keep the existing `apply` and `resource` methods on `RabbitClient`, and deprecate them - pointing to the new builder class? That makes it easier for people to make the change when they upgrade.

**Comment by retriku** [comment]
@jbwheatley done!

**Pull request merged**
